import { ProductUnit } from "../src/generated/prisma/enums";

export const seasonalCategories = [
  { name: "Фрукты", slug: "frukty", sortOrder: 1 },
  { name: "Овощи", slug: "ovoschi", sortOrder: 2 },
  { name: "Картофель", slug: "kartofel", sortOrder: 3 },
  { name: "Зелень", slug: "zelen", sortOrder: 4 },
  { name: "Ягоды", slug: "yagody", sortOrder: 5 },
  { name: "Грибы", slug: "griby", sortOrder: 6 },
  { name: "Экзотика", slug: "ekzotika", sortOrder: 7 },
  { name: "Готовые наборы", slug: "nabory", sortOrder: 8 },
  { name: "Акции", slug: "aktsii", sortOrder: 9 },
];

const seasonalProductsRaw = [
  {
    categorySlug: "ovoschi",
    name: "Помидоры Парадайс розовые",
    description: "Сладкие розовые томаты. Ящики 7-8 кг.",
    price: 220,
    unit: ProductUnit.KG,
    imageUrl: "/products/tomatoes.webp",
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Помидоры Парадайс розовые нестандартные",
    description: "Сладкие розовые томаты нестандартного калибра. Ящики 7-8 кг.",
    price: 220,
    unit: ProductUnit.KG,
    imageUrl: "/products/tomatoes.webp",
    isHit: false,
    isNew: false,
    isPromo: true,
  },
  {
    categorySlug: "ovoschi",
    name: "Помидор красный Махитос",
    description: "Красный томат Махитос. Продажа от 5 кг.",
    price: 250,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Помидоры красные Таганрог",
    description: "Красные таганрогские томаты. Продажа от 5 кг.",
    price: 350,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Болгарский перец красный-желтый",
    description: "Сладкий болгарский перец. Ящик 4,5 кг.",
    price: 200,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Баклажаны",
    description: "Свежие баклажаны. Ящик 6-7 кг.",
    price: 250,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Кукуруза",
    description: "Кукуруза в початках. Продажа от 10 шт.",
    price: 170,
    unit: ProductUnit.PIECE,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Огурец пупырка Багаевка",
    description: "Хрустящий огурец. Продажа от 10 кг, ящик 23-25 кг.",
    price: 150,
    unit: ProductUnit.KG,
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Огурец Зозуля",
    description: "Огурец Зозуля. Ящик 10 кг.",
    price: 200,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Редиска",
    description: "Свежая редиска к сезонному столу.",
    price: 150,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Черри Кривянка сладкий",
    description: "Сладкие черри Кривянка. Ящик 8-9 кг.",
    price: 500,
    unit: ProductUnit.KG,
    imageUrl: "/products/tomatoes.webp",
    isHit: true,
    isNew: false,
    isPromo: true,
  },
  {
    categorySlug: "kartofel",
    name: "Картофель Гала",
    description: "Картофель сорта Гала. Мешок 25-30 кг.",
    price: 55,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "kartofel",
    name: "Картофель Родриго",
    description: "Картофель сорта Родриго. Мешок 25-30 кг.",
    price: 55,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "kartofel",
    name: "Картофель Коломбо",
    description: "Картофель сорта Коломбо. Мешок 25-35 кг.",
    price: 55,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "kartofel",
    name: "Картофель Королева Анна",
    description: "Картофель сорта Королева Анна. Мешок 25-35 кг.",
    price: 55,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "kartofel",
    name: "Картофель Вега",
    description: "Картофель сорта Вега. Мешок 25-35 кг.",
    price: 55,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "kartofel",
    name: "Краснодарский картофель",
    description: "Краснодарский картофель. Мешок 34-37 кг.",
    price: 70,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Морковь",
    description: "Морковь от 5 кг. При заказе от 20 кг цена остается 50 ₽/кг.",
    price: 50,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Свекла",
    description: "Свекла от 5 кг. При заказе от 20 кг цена остается 50 ₽/кг.",
    price: 50,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Лук зимний",
    description: "Зимний лук от 5 кг. Мешки 30-33 кг, мешком 35 ₽/кг.",
    price: 50,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: true,
  },
  {
    categorySlug: "ovoschi",
    name: "Кабачки",
    description: "Кабачки. Продажа от 5 кг.",
    price: 150,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Капуста молодая",
    description: "Молодая капуста нового сезона.",
    price: 170,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Капуста белокочанная 3 вида",
    description: "Белокочанная капуста, три вида. Продажа от 5 кг.",
    price: 50,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Чеснок крупный синий",
    description: "Крупный синий чеснок.",
    price: 320,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Острый перец красный",
    description: "Красный острый перец. Цена указана за 0,5 кг.",
    price: 600,
    unit: ProductUnit.PACK,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Острый перец зеленый Армения",
    description: "Зеленый острый перец из Армении.",
    price: 1000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Цветная капуста",
    description: "Цветная капуста. Продажа от 5 кг.",
    price: 220,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Брокколи",
    description: "Свежая брокколи. Продажа от 5 кг.",
    price: 350,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Лист салата",
    description: "Листовой салат для свежих миксов.",
    price: 500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Лола Росса",
    description: "Салат Лола Росса.",
    price: 800,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Шпинат",
    description: "Свежий шпинат.",
    price: 500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Руккола",
    description: "Ароматная руккола.",
    price: 600,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Петрушка Грузия",
    description: "Свежая петрушка из Грузии.",
    price: 500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Укроп Грузия",
    description: "Свежий укроп из Грузии.",
    price: 500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Лук зеленый",
    description: "Зеленый лук.",
    price: 600,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Базилик темный",
    description: "Темный базилик.",
    price: 1000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Базилик зеленый",
    description: "Зеленый базилик. Цена нормализована как 1000 ₽/кг по аналогии с темным базиликом.",
    price: 1000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Кинза",
    description: "Свежая кинза.",
    price: 500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Щавель",
    description: "Свежий щавель.",
    price: 500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Спаржа крупная Краснодар",
    description: "Крупная краснодарская спаржа.",
    price: 1500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Пекинская капуста",
    description: "Пекинская капуста.",
    price: 120,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Клубника Турция, Азербайджан",
    description: "Клубника Турция/Азербайджан. Прайс 300-350 ₽/кг, ящик 4 кг.",
    price: 300,
    unit: ProductUnit.KG,
    imageUrl: "/products/strawberries.webp",
    isHit: true,
    isNew: true,
    isPromo: true,
  },
  {
    categorySlug: "yagody",
    name: "Клубника Ростовская сладкая",
    description: "Ростовская сладкая клубника. Диапазон 300-500 ₽/кг, ящик 5-5,5 кг.",
    price: 300,
    unit: ProductUnit.KG,
    imageUrl: "/products/strawberries.webp",
    isHit: true,
    isNew: true,
    isPromo: true,
  },
  {
    categorySlug: "yagody",
    name: "Голубика",
    description: "Голубика. Диапазон по прайсу: 1200/1700/2000 ₽/кг.",
    price: 1200,
    unit: ProductUnit.KG,
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Черешня Узбекистан",
    description: "Черешня Узбекистан от 850 ₽/кг. Ящик 4 кг.",
    price: 850,
    unit: ProductUnit.KG,
    imageUrl: "/products/cherries.webp",
    isHit: true,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Вишня",
    description: "Вишня. Ящик 4 кг.",
    price: 500,
    unit: ProductUnit.KG,
    imageUrl: "/products/cherries.webp",
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Нектарины узбекские",
    description: "Узбекские нектарины. Ящик 5 кг.",
    price: 600,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Нектарины турецкие",
    description: "Турецкие нектарины. Ящик 2-3 кг.",
    price: 550,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Яблоки отборные сорт на выбор",
    description: "Отборные яблоки, сорт на выбор. Ящик 15 кг.",
    price: 190,
    unit: ProductUnit.KG,
    imageUrl: "/products/apples.webp",
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Яблоко среднего размера",
    description: "Яблоко среднего размера. Ящик 16-17 кг.",
    price: 140,
    unit: ProductUnit.KG,
    imageUrl: "/products/apples.webp",
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "griby",
    name: "Шампиньоны крупные, средние, обычные",
    description: "Шампиньоны разных калибров. Ящики 3 кг.",
    price: 300,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "griby",
    name: "Шампиньоны Горох",
    description: "Шампиньоны Горох. Ящик 3 кг.",
    price: 350,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "griby",
    name: "Вешенки",
    description: "Вешенки. Ящик 3-5 кг.",
    price: 300,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Груша лампочка",
    description: "Груша лампочка. Ящик 6-7 кг.",
    price: 250,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Груша конференция Бельгия",
    description: "Груша конференция из Бельгии. Ящик 12-13 кг.",
    price: 330,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Апельсин Красный",
    description: "Красный апельсин. Ящик 15 кг.",
    price: 200,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Грейпфрут",
    description: "Грейпфрут. Ящик 7-15 кг.",
    price: 160,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Апельсин Египет",
    description: "Сочный апельсин Египет. Ящик 7-8 кг.",
    price: 120,
    unit: ProductUnit.KG,
    isHit: true,
    isNew: false,
    isPromo: true,
  },
  {
    categorySlug: "frukty",
    name: "Киви",
    description: "Киви. Ящик 4 кг.",
    price: 180,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Алыча",
    description: "Алыча по сезонному прайсу.",
    price: 1200,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Манго премиум",
    description: "Премиальное манго.",
    price: 800,
    unit: ProductUnit.PIECE,
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Манго смайлик",
    description: "Манго смайлик. Ящик 15 шт., можно штучно.",
    price: 250,
    unit: ProductUnit.PIECE,
    isHit: false,
    isNew: false,
    isPromo: true,
  },
  {
    categorySlug: "ekzotika",
    name: "Ананас мини",
    description: "Мини-ананас. Ящик 9 шт.",
    price: 650,
    unit: ProductUnit.PIECE,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Ананас спелый Gold крупный",
    description: "Крупный спелый ананас Gold.",
    price: 900,
    unit: ProductUnit.PIECE,
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Ананас Gold средний",
    description: "Средний ананас Gold.",
    price: 700,
    unit: ProductUnit.PIECE,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Драгон фрукт (Питахайя)",
    description: "Питахайя, любой цвет.",
    price: 1000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Кокос питьевой",
    description: "Питьевой кокос.",
    price: 500,
    unit: ProductUnit.PIECE,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Мангостан",
    description: "Крупный тайский мангостан.",
    price: 250,
    unit: ProductUnit.PIECE,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Гуава",
    description: "Гуава, можно штучно.",
    price: 2000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Папайя Gold",
    description: "Папайя Gold.",
    price: 2000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Голубика премиум",
    description: "Премиальная голубика. Диапазон 1800-2000 ₽/кг.",
    price: 1800,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Красная смородина",
    description: "Красная смородина. Цена за упаковку.",
    price: 700,
    unit: ProductUnit.PACK,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Гранадила",
    description: "Гранадила. Ящик 4500 ₽, в ящике 17-18 шт.",
    price: 300,
    unit: ProductUnit.PIECE,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Маракуйя Тай",
    description: "Тайская маракуйя. Пачка 1 кг.",
    price: 2500,
    unit: ProductUnit.PACK,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Рамбутан",
    description: "Рамбутан.",
    price: 2500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ekzotika",
    name: "Дуриан",
    description: "Дуриан. Плод обычно от 2 до 4 кг.",
    price: 2500,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Малина Крым",
    description: "Крымская малина. Продажа от 0,4 кг.",
    price: 4000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Ежевика Крым",
    description: "Крымская ежевика. Продажа от 0,5 кг.",
    price: 3000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Молодой горох",
    description: "Молодой горох.",
    price: 400,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Арбузы Тай или Иран",
    description: "Арбузы Тай или Иран.",
    price: 150,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Алыча сезонная",
    description: "Алыча по дополнительному прайсу.",
    price: 1000,
    unit: ProductUnit.KG,
    isHit: false,
    isNew: true,
    isPromo: true,
  },
  {
    categorySlug: "zelen",
    name: "Мята свежая",
    description: "Пучок ароматной свежей мяты для напитков и десертов.",
    price: 120,
    unit: ProductUnit.PACK,
    imageUrl: "/products/fresh-mint.webp",
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "nabory",
    name: "Набор на неделю",
    description: "Собранный набор фруктов, овощей и зелени для семьи из 3-4 человек.",
    price: 1890,
    unit: ProductUnit.PIECE,
    imageUrl: "/products/weekly-box.webp",
    isHit: true,
    isNew: false,
    isPromo: true,
  },
];

const productImages: Record<string, string> = {
  "Помидоры Парадайс розовые": "/products/tomatoes.webp",
  "Помидоры Парадайс розовые нестандартные": "/products/tomatoes.webp",
  "Помидор красный Махитос": "/products/tomatoes.webp",
  "Помидоры красные Таганрог": "/products/tomatoes.webp",
  "Болгарский перец красный-желтый": "/products/bell-peppers.webp",
  Баклажаны: "/products/eggplants.webp",
  Кукуруза: "/products/corn.webp",
  "Огурец пупырка Багаевка": "/products/cucumbers.webp",
  "Огурец Зозуля": "/products/cucumbers.webp",
  Редиска: "/products/radishes.webp",
  "Черри Кривянка сладкий": "/products/tomatoes.webp",
  "Картофель Гала": "/products/potatoes.webp",
  "Картофель Родриго": "/products/potatoes.webp",
  "Картофель Коломбо": "/products/potatoes.webp",
  "Картофель Королева Анна": "/products/potatoes.webp",
  "Картофель Вега": "/products/potatoes.webp",
  "Краснодарский картофель": "/products/potatoes.webp",
  Морковь: "/products/root-vegetables.webp",
  Свекла: "/products/root-vegetables.webp",
  "Лук зимний": "/products/root-vegetables.webp",
  Кабачки: "/products/zucchini.webp",
  "Капуста молодая": "/products/cabbage.webp",
  "Капуста белокочанная 3 вида": "/products/cabbage.webp",
  "Чеснок крупный синий": "/products/garlic-chili.webp",
  "Острый перец красный": "/products/garlic-chili.webp",
  "Острый перец зеленый Армения": "/products/garlic-chili.webp",
  "Цветная капуста": "/products/cauliflower-broccoli.webp",
  Брокколи: "/products/cauliflower-broccoli.webp",
  "Лист салата": "/products/leafy-greens.webp",
  "Лола Росса": "/products/leafy-greens.webp",
  Шпинат: "/products/leafy-greens.webp",
  Руккола: "/products/leafy-greens.webp",
  "Петрушка Грузия": "/products/herbs-bundle.webp",
  "Укроп Грузия": "/products/herbs-bundle.webp",
  "Лук зеленый": "/products/herbs-bundle.webp",
  "Базилик темный": "/products/herbs-bundle.webp",
  "Базилик зеленый": "/products/herbs-bundle.webp",
  Кинза: "/products/herbs-bundle.webp",
  Щавель: "/products/herbs-bundle.webp",
  "Спаржа крупная Краснодар": "/products/asparagus.webp",
  "Пекинская капуста": "/products/cabbage.webp",
  "Клубника Турция, Азербайджан": "/products/strawberries.webp",
  "Клубника Ростовская сладкая": "/products/strawberries.webp",
  Голубика: "/products/blueberries.webp",
  "Черешня Узбекистан": "/products/cherries.webp",
  Вишня: "/products/cherries.webp",
  "Нектарины узбекские": "/products/nectarines-plums.webp",
  "Нектарины турецкие": "/products/nectarines-plums.webp",
  "Яблоки отборные сорт на выбор": "/products/apples.webp",
  "Яблоко среднего размера": "/products/apples.webp",
  "Шампиньоны крупные, средние, обычные": "/products/mushrooms.webp",
  "Шампиньоны Горох": "/products/mushrooms.webp",
  Вешенки: "/products/mushrooms.webp",
  "Груша лампочка": "/products/pears.webp",
  "Груша конференция Бельгия": "/products/pears.webp",
  "Апельсин Красный": "/products/citrus-kiwi.webp",
  Грейпфрут: "/products/citrus-kiwi.webp",
  "Апельсин Египет": "/products/citrus-kiwi.webp",
  Киви: "/products/citrus-kiwi.webp",
  Алыча: "/products/nectarines-plums.webp",
  "Манго премиум": "/products/mangoes.webp",
  "Манго смайлик": "/products/mangoes.webp",
  "Ананас мини": "/products/pineapples.webp",
  "Ананас спелый Gold крупный": "/products/pineapples.webp",
  "Ананас Gold средний": "/products/pineapples.webp",
  "Драгон фрукт (Питахайя)": "/products/dragon-fruit.webp",
  "Кокос питьевой": "/products/coconuts.webp",
  Мангостан: "/products/tropical-exotic.webp",
  Гуава: "/products/tropical-exotic.webp",
  "Папайя Gold": "/products/tropical-exotic.webp",
  "Голубика премиум": "/products/blueberries.webp",
  "Красная смородина": "/products/red-currants.webp",
  Гранадила: "/products/tropical-exotic.webp",
  "Маракуйя Тай": "/products/tropical-exotic.webp",
  Рамбутан: "/products/tropical-exotic.webp",
  Дуриан: "/products/tropical-exotic.webp",
  "Малина Крым": "/products/raspberries-blackberries.webp",
  "Ежевика Крым": "/products/raspberries-blackberries.webp",
  "Молодой горох": "/products/green-peas.webp",
  "Арбузы Тай или Иран": "/products/watermelons.webp",
  "Алыча сезонная": "/products/nectarines-plums.webp",
  "Мята свежая": "/products/fresh-mint.webp",
  "Набор на неделю": "/products/weekly-box.webp",
};

export const seasonalProducts = seasonalProductsRaw.map((product) => ({
  ...product,
  imageUrl: product.imageUrl ?? productImages[product.name] ?? "/products/weekly-box.webp",
}));
