import { ProductUnit } from "../src/generated/prisma/enums";

type SeasonalCategory = {
  name: string;
  slug: string;
  imageUrl: string;
  sortOrder: number;
  isActive: boolean;
};

type SeasonalProduct = {
  categorySlug: string;
  name: string;
  description: string;
  price: number;
  unit: ProductUnit;
  imageUrl: string;
  isHit: boolean;
  isNew: boolean;
  isPromo: boolean;
};

const productImage = (slug: string) => `/products/market-2026/${slug}.webp`;

export const seasonalCategories: SeasonalCategory[] = [
  {
    name: "Ягоды",
    slug: "yagody",
    imageUrl: productImage("klubnika-rostov-sort-kleri"),
    sortOrder: 10,
    isActive: true,
  },
  {
    name: "Фрукты",
    slug: "frukty",
    imageUrl: productImage("abrikosy-uzbekskie"),
    sortOrder: 20,
    isActive: true,
  },
  {
    name: "Овощи",
    slug: "ovoschi",
    imageUrl: productImage("pomidory-mahitos-bagaevka"),
    sortOrder: 30,
    isActive: true,
  },
  {
    name: "Картофель",
    slug: "kartofel",
    imageUrl: productImage("kartofel-molodoy"),
    sortOrder: 40,
    isActive: true,
  },
  {
    name: "Зелень",
    slug: "zelen",
    imageUrl: productImage("shpinat"),
    sortOrder: 50,
    isActive: true,
  },
];

export const seasonalProducts: SeasonalProduct[] = [
  {
    categorySlug: "frukty",
    name: "Абрикосы узбекские",
    description: "Спелые узбекские абрикосы из свежей сезонной поставки.",
    price: 400,
    unit: ProductUnit.KG,
    imageUrl: productImage("abrikosy-uzbekskie"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Клубника Краснодар",
    description: "Краснодарская клубника для десертов, завтраков и свежих ягодных тарелок.",
    price: 250,
    unit: ProductUnit.KG,
    imageUrl: productImage("klubnika-krasnodar"),
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Малина Краснодар",
    description: "Нежная краснодарская малина в аккуратной фасовке.",
    price: 1700,
    unit: ProductUnit.KG,
    imageUrl: productImage("malina-krasnodar"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Ежевика Краснодар",
    description: "Крупная ежевика с насыщенным вкусом и плотной ягодой.",
    price: 1700,
    unit: ProductUnit.KG,
    imageUrl: productImage("ezhevika-krasnodar"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Баклажаны багаевка",
    description: "Глянцевые баклажаны из Багаевки для запекания, икры и горячих блюд.",
    price: 200,
    unit: ProductUnit.KG,
    imageUrl: productImage("baklazhany-bagaevka"),
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Болгарский перец багаевка",
    description: "Сочный болгарский перец с плотной стенкой.",
    price: 250,
    unit: ProductUnit.KG,
    imageUrl: productImage("bolgarskiy-perets-bagaevka"),
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Помидоры махитос багаевка",
    description: "Красные помидоры Махитос из Багаевки для салатов и нарезки.",
    price: 230,
    unit: ProductUnit.KG,
    imageUrl: productImage("pomidory-mahitos-bagaevka"),
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Клубника Краснодар сорт Азия",
    description: "Сладкая краснодарская клубника сорта Азия.",
    price: 350,
    unit: ProductUnit.KG,
    imageUrl: productImage("klubnika-krasnodar-sort-aziya"),
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "kartofel",
    name: "Картофель молодой",
    description: "Молодой картофель для варки, запекания и летних гарниров.",
    price: 90,
    unit: ProductUnit.KG,
    imageUrl: productImage("kartofel-molodoy"),
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Слива Узбекистан",
    description: "Узбекская слива с плотной мякотью и ярким сладким вкусом.",
    price: 250,
    unit: ProductUnit.KG,
    imageUrl: productImage("sliva-uzbekistan"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Вишня",
    description: "Сочная сезонная вишня для компотов, десертов и свежей подачи.",
    price: 400,
    unit: ProductUnit.KG,
    imageUrl: productImage("vishnya"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Огурец Багаевка",
    description: "Хрустящий багаевский огурец для салатов и свежих закусок.",
    price: 90,
    unit: ProductUnit.KG,
    imageUrl: productImage("ogurets-bagaevka"),
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Клубника Ростов сорт Клери",
    description: "Ростовская клубника сорта Клери. Хит продаж.",
    price: 250,
    unit: ProductUnit.KG,
    imageUrl: productImage("klubnika-rostov-sort-kleri"),
    isHit: true,
    isNew: false,
    isPromo: true,
  },
  {
    categorySlug: "ovoschi",
    name: "Брокколи багаевка",
    description: "Свежая брокколи из Багаевки для гарниров и полезных блюд.",
    price: 250,
    unit: ProductUnit.KG,
    imageUrl: productImage("brokkoli-bagaevka"),
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Нектарины турецкие",
    description: "Ароматные турецкие нектарины с плотной сладкой мякотью.",
    price: 300,
    unit: ProductUnit.KG,
    imageUrl: productImage("nektariny-turetskie"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "frukty",
    name: "Арбуз Казахстан или Иран",
    description: "Сочный сезонный арбуз из актуальной поставки.",
    price: 90,
    unit: ProductUnit.KG,
    imageUrl: productImage("arbuz-kazahstan-iran"),
    isHit: true,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "yagody",
    name: "Крыжовник",
    description: "Свежий зелёный крыжовник для компотов, выпечки и свежей подачи.",
    price: 600,
    unit: ProductUnit.KG,
    imageUrl: productImage("kryzhovnik"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Горох",
    description: "Молодой зелёный горох в стручках.",
    price: 350,
    unit: ProductUnit.KG,
    imageUrl: productImage("goroh"),
    isHit: false,
    isNew: true,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Зозуля",
    description: "Огурец Зозуля для свежих салатов и домашней кухни.",
    price: 250,
    unit: ProductUnit.KG,
    imageUrl: productImage("zozulya"),
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "zelen",
    name: "Шпинат",
    description: "Свежий шпинат для салатов, смузи и горячих блюд.",
    price: 500,
    unit: ProductUnit.KG,
    imageUrl: productImage("shpinat"),
    isHit: false,
    isNew: false,
    isPromo: false,
  },
  {
    categorySlug: "ovoschi",
    name: "Помидоры азербайджанский красный",
    description: "Красные азербайджанские помидоры с насыщенным томатным вкусом.",
    price: 250,
    unit: ProductUnit.KG,
    imageUrl: productImage("pomidory-azerbaydzhanskiy-krasnyy"),
    isHit: false,
    isNew: false,
    isPromo: false,
  },
];
